name: CI - Run Tests

on:
  pull_request:
    branches:
      - master # Replace 'main' with your default branch name if it's different

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use the Node.js version compatible with your project
          cache: 'pnpm'

      # Step 3: Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Step 4: Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Step 5: Run tests
      - name: Run tests
        run: pnpm test